package ru.firsov.study.Java.Telegram.Bot.common;

public enum BotState {
    DEFAULT,
    SELECTING_TYPE,
    SELECTING_PART,
    SELECTING_CHAPTER,
    TESTING,
    LEARNING,

    ADMIN_LOGIN,
    ADMIN_PAGE,
    ADMIN_WAIT_MSG,
    ADMIN_EDIT,
    ADMIN_EDIT_ANSWER,
    ADMIN_EDIT_QUESTION,

    ADMIN_ADD_QUESTION_SELECT_PART,
    ADMIN_ADD_QUESTION_SELECT_CHAPTER,
    ADMIN_ADD_QUESTION_ENTER,

    ADMIN_ADD_CHAPTER_SELECT_PART,
    ADMIN_ADD_CHAPTER_ENTER,
    ;
}
