name: Deploy container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ARM64
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker-Container
      run: make    
    - name: Deploy container
      run: ssh ${{ secrets.HOST_USER }}@${{ secrets.HOST_ADDRESS }} "docker pull ${{ secrets.DOCKER_IMAGE }} && docker run ${{ secrets.DOCKER_RUNPARAMS }} ${{ secrets.DOCKER_IMAGE }}"
