name: Deploy container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
#     runs-on: ARM64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
#     - name: Build Docker-Container
#       run: make    
   
    - name: Deploy container via ssh command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.HOST_USER }}
        port: ${{ secrets.HOST_PORT }}
        key: ${{ secrets.HOST_KEY }}
        script: |
          whoami
          docker pull ${{ secrets.DOCKER_IMAGE }}
          docker run ${{ secrets.DOCKER_RUNPARAMS }} ${{ secrets.DOCKER_IMAGE }}
