name: Deploy with makefile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ARM64
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker-Container
      run: make
    
    - name: Deploy container
      run: ssh ${{ host.USER }}@${{ host.ADDRESS }} "docker pull ${{ docker.IMAGE }} && docker run ${{ docker.RUNPARAMS }} ${{ docker.IMAGE }}"
