name: Deploy container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
#     runs-on: ARM64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up QEMU #(for support many platforms)
      uses: docker/setup-qemu-action@v1
      
    - name: Build Jar
      run: make    
    
    - uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    
      
    - name: Build Docker container
      run: |
          docker buildx build 
          --tag ${{ secrets.DOCKER_IMAGE }} 
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
#          docker build . --platform linux/arm64 # will run buildx
          
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ secrets.DOCKER_IMAGE }}
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    
    - name: Deploy container via ssh command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.HOST_USER }}
        port: ${{ secrets.HOST_PORT }}
        key: ${{ secrets.HOST_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_IMAGE }}
          docker stop learning-tg-bot
          docker rm learning-tg-bot
          docker run ${{ secrets.DOCKER_RUNPARAMS }} ${{ secrets.DOCKER_IMAGE }}
